### ISSUE TITLE
Pushvars fails to parse when an config includes inline templates

### ISSUE THREAD

**Issue by dotspec** [hashicorp/tfe-cli#22]
I'm migrating a bunch of environments from the legacy TFE and most have gone ok when doing an initial `tfe pushvars -name org/env -tfe-address https://tfe.ourinstance.com` however I ran into a few that after doing the initial curl to get the environment's variables just silently quit.  The (truncated) debug outlook looks like this.

>shell-> TF_LOG=DEBUG tfe pushvars -name org/env -tfe-address https://tfe.ourinstance.com .
[DEBUG] API list variables URL:
https://tfe.ourinstance.com/api/v2/vars?filter%5Borganization%5D%5Bname%5D=bsg&filter%5Bworkspace%5D%5Bname%5D=longevity
[DEBUG] API request for variable list:
API request succeeded. Response:
{"data":[{"id":"var-SZ94t4zHKbF8KaV7","type":"vars","attributes":{"key":"var-a","value":var-b,"sensitive":true,"category":"env","hcl":false}]}
[DEBUG] All variables:

After some troubleshooting I started removing files from the directory and got it to the point where it'd parse our variables so that the output above would include the variable list at the bottom as you'd expect. 

>[DEBUG] All variables:
var_a
var_b
var_c

Once I found the offending file I started removing resources until I narrowed it down to an aws_iam_policy resource that has an inline JSON policy.  Once that policy was commented out `pushvars` completes successfully.  I've observed this with a couple environments now, both of which had inline templates.  I'm still going through the tfe-cli pushvars comand to figure out why it's failing but figured it'd be worth opening an issue in the meantime.

**Comment by fprimex** [comment]
Hi, thanks for the report. Could you share the structure of the declaration of the policy? I may be able to fix the parser to avoid them. As you may be able to guess, this is not strictly a valid HCL parser, but rather an elaborate `awk` that looks for specific things. It probably just needs some tweaking.

**Comment by dotspec** [comment]
Sure thing.  Here's the policy it chokes on.

`resource "aws_iam_policy" "the-offending-policy" {
  name = "the-offending-policy"
  policy = <<EOF
  {
      "Version": "2012-10-17",
      "Statement": [
          {
              "Effect": "Allow",
              "Action": "s3:ListAllMyBuckets",
              "Resource": "arn:aws-endpoint:s3:::*"
          },
          {
              "Effect": "Allow",
              "Action": [
                "s3:DeleteObject",
                "s3:GetBucketAcl",
                "s3:GetBucketPolicy",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:ListAllMyBuckets",
                "s3:ListBucket",
                "s3:PutObject"
              ],
              "Resource": [
                  "arn:aws-endpoint:s3:::a-bucket/*"
              ]
          },
          {
              "Effect": "Allow",
              "Action": [
                "s3:GetBucketAcl",
                "s3:GetBucketPolicy",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:ListAllMyBuckets",
                "s3:ListBucket"
              ],
              "Resource": [
                  "arn:aws-endpoint:s3:::another-bucket/*",
                  "arn:aws-endpoint:s3:::another-bucket/*"
              ]
          },
          {
              "Effect": "Allow",
              "Action": [
                  "s3:ListBucket",
                  "s3:GetBucketLocation"
              ],
              "Resource": [
                  "arn:aws-endpoint:s3:::another-bucket",
                  "arn:aws-endpoint:s3:::another-bucket",
                  "arn:aws-endpoint:s3:::another-bucket"
              ]
          },
          {
            "Sid": "Stmt1485887111000",
            "Effect": "Allow",
            "Action": [
              "sqs:ChangeMessageVisibility",
              "sqs:ChangeMessageVisibilityBatch",
              "sqs:DeleteMessage",
              "sqs:DeleteMessageBatch",
              "sqs:GetQueueAttributes",
              "sqs:GetQueueUrl",
              "sqs:ListDeadLetterSourceQueues",
              "sqs:ListQueues",
              "sqs:ReceiveMessage"
            ],
            "Resource": [
              "arn:aws-endpoint:sqs:aws-region:aws-id:another-bucket"
            ]
          },
          {
            "Effect": "Allow",
            "Action": [
              "sqs:ChangeMessageVisibility",
              "sqs:ChangeMessageVisibilityBatch",
              "sqs:GetQueueAttributes",
              "sqs:GetQueueUrl",
              "sqs:ListDeadLetterSourceQueues",
              "sqs:ListQueues",
              "sqs:SendMessage",
              "sqs:SendMessageBatch"
            ],
            "Resource": [
              "arn:aws-endpoint:sqs:aws-region:aws-id:another-bucket"
            ]
          }
      ]
  }
EOF
}
`

And for what it's worth there's an aws_iam_role resource in that same file that it doesn't have any trouble with.

`
resource "aws_iam_role" "the-good-role" {
  name               = "the-good-role"
  assume_role_policy = <<EOF
{
"Version": "2012-10-17",
"Statement": [
  {
    "Action": "sts:AssumeRole",
    "Principal": {
      "Service": "ec2.amazonaws.com"
    },
    "Effect": "Allow",
    "Sid": ""
  }
]
}
EOF
}
`

**Comment by fprimex** [comment]
Hi, sorry about the lack of update here. I've not actually been able to reproduce this - it could have something to do with the formatting. Could you gist how this is formatted in your configuration, and let me know what order these things appear, or if they're in different files (and the file names)?

Hopefully you have been able to work around this issue, but if not, consider moving the variable above the resource if it's below.

**Comment by fprimex** [comment]
There was one fix for space handling pushed yesterday that might help depending on how things are formatted.

**Comment by fprimex** [comment]
It's been a bummer that I haven't been able to reproduce this. If you can send the formatted files that would help. As a customer (since you are a TFE user), you have access to our paid support and the help desk portal, where you could share with us the complete file(s) in a private, secure way. If you'd like to pick this up in that manner just email us at `support@hashicorp.com`, or visit `https://support.hashicorp.com`. Mention this ticket or `tfe-cli` and I will pick it up. Thanks!
