### ISSUE TITLE
ssh configuration workspace new

### ISSUE THREAD

**Issue by fdavier** [hashicorp/tfe-cli#25]
Hi, i worked on gitlab ci process wich create workspace in saas TFE. I need some function / option to choose ssh key to deploy.
Suggestion --> tfe workspace new -name <ORGANIZATION>/<WORKSPACE> -ssh <SSHKEY>

Regards

**Comment by fprimex** [comment]
Hi, thanks for the suggestion. Generally speaking, other than the very overloaded `pushconfig`, `pushvars`, and `pullvars` commands (which were aimed at replacing `terraform push`), the newer commands target a single API endpoint. In the case of SSH keys, there is an API for creating them independently of workspace operations, and then an API endpoint for assigning and another for unassigning them to the workspace(s).

What is _likely_ to happen in the near term is that we'll keep the `tfe workspace new` command only dealing with the options that pertain to the one API operation for creating a workspace, and then we'll do the same for SSH keys. So, ultimately creating a workspace, creating a key, and assigning the key to the workspace would be three operations with the CLI.

However, a more complete, mature design for the CLI is being worked on right now, and it may be the case that we're OK with expanding the scope of the operations to be more complex so as to provide more convenience.

I will add this issue to that discussion so we can consider this in the updated design in general, and if we go in this direction we'll be happy to add such an option.

Cheers

**Comment by robinbowes** [comment]
I need the same functionality. I'm using the tfe provider for everything else, but it doesn't assign ssh keys to workspaces either. Looks like I'll need to hit the API.

**Comment by fprimex** [comment]
👋 I've implemented `tfe ssh` commands, including `tfe ssh assign`. If you are OK with running two commands, it's now possible to `tfe workspace new ...` and then `tfe ssh assign ...` (and, if you want, create or update the SSH keys themselves).

Would this work sufficiently, or is there a use case where having an all-in-one `tfe workspace new` with an `-ssh` option? Such an option would just do the work of both commands, and could complicate the error checking (e.g. successfully creating the workspace but then failing to assign the SSH key).

This is implemented in the overhaul branch called `update` if you'd like to give it a try:

https://github.com/hashicorp/tfe-cli/tree/update

**Comment by fprimex** [comment]
I've merged the `ssh` commands into master and tagged v0.1.0 (first tag!). If you hit any issues or have another use case just let me know. Cheers.
