### ISSUE TITLE
pushconfig should have a 'message' flag to set the run's message

### ISSUE THREAD

**Issue by syalam** [hashicorp/tfe-cli#26]
When deploying using tfe pushconfig the operator should be allowed to attach a message so that the run message is human readable in TFE. 

At the moment all runs default to: 

> "Queued manually via the Terraform Enterprise API"

**Example Usage:**
tfe pushconfig -name myworkspace -message "a commit message"

**Comment by fprimex** [comment]
Hi, please give this new branch a try to see if it works for you. It adds `-message` to `pushconfig`. I had one submission that failed to obtain a run ID and I'm not sure what happened there. If you hit anything like that let me know. Could have been on the service side.

https://github.com/hashicorp/tfe-cli/tree/push_msg

**Comment by syalam** [comment]
LGTM

Sheehan Alam
www.syalam.com

**Comment by fprimex** [comment]
merged into master finally :)
