### ISSUE TITLE
pushvars skips raw boolean variables

### ISSUE THREAD

**Issue by jeremygaither** [hashicorp/tfe-cli#34]
If a variable is defined like this:

``` hcl
variable "enable_monitoring" {
  default = true # SKIPPED
}
```

Then `tfe pushvars -var-file ...` will skip declaring and adding the variable.

Debug output:

```
[DEBUG] Temporary directory contents:
env-xyz.tfvars
vars.tf
[DEBUG] Temporary file contents:
app_name = "..."

environment_label = "..."

server_environment = "..."

vpc_id = "..."

subnets = ["..."]

security_groups = ["..."]

ssl_certificate_arn = "..."

waf_webacl_id = "..."

target_instance_names = [
  "...",
]

alert_eval_mins = "..."

enable_monitoring = false
variable "app_name" {}
variable "environment_label" {}
variable "server_environment" {}
variable "vpc_id" {}
variable "subnets" {}
variable "security_groups" {}
variable "ssl_certificate_arn" {}
variable "waf_webacl_id" {}
variable "target_instance_names" {}
variable "alert_eval_mins" {}
[DEBUG] All variables:
app_name
environment_label
server_environment
vpc_id
subnets
security_groups
ssl_certificate_arn
waf_webacl_id
target_instance_names
alert_eval_mins
```

However, when the boolean value is quoted in the original variable declaration, `tfe pushvars` works as expected:

``` hcl
variable "enable_monitoring" {
  default = "true" # WORKS
}
```

**Comment by fprimex** [comment]
Hi, thanks for bringing this to my attention. Please note that the recommendation for bools is to use `"true"` and `"false"` as noted here:

https://www.terraform.io/docs/configuration/variables.html#booleans

Nevertheless, this should work with `pushvars`. I have been working on a branch that has some significant changes so I am adding this on top of that work. You can try this out by checking out the `update` branch:

https://github.com/hashicorp/tfe-cli/tree/update

There is a detail regarding the handling of bools you should be aware of when using `tfe`. The `tfe` command uses `terraform console` to extract the values of the variables. This means that the bool conversion process applies. So, if raw booleans are used, then the conversion process will produce either `"1"` or `"0"`, as in the following.

```
variable "foo0" { default = true }
variable "foo1" { default = "true" }
variable "foo2" { default = "1" }
variable "bar0" { default = false }
variable "bar1" { default = "false" }
variable "bar2" { default = "0" }

output "f0" { value = "${var.foo0 ? "is true" : "is false"}" }
output "f1" { value = "${var.foo1 ? "is true" : "is false"}" }
output "f2" { value = "${var.foo2 ? "is true" : "is false"}" }
output "b0" { value = "${var.bar0 ? "is true" : "is false"}" } 
output "b1" { value = "${var.bar1 ? "is true" : "is false"}" }
output "b2" { value = "${var.bar2 ? "is true" : "is false"}" }
```

Terraform evaluates the above in an apply as:

```
f0 = is true
f1 = is true
f2 = is true
b0 = is false
b1 = is false
b2 = is false
```

And `tfe` will push the values

```
$ tfe pushvars -dry-run 1 .
Creating foo0 type:terraform hcl:false sensitive:false value:1
Creating foo1 type:terraform hcl:false sensitive:false value:true
Creating foo2 type:terraform hcl:false sensitive:false value:1
Creating bar0 type:terraform hcl:false sensitive:false value:0
Creating bar1 type:terraform hcl:false sensitive:false value:false
Creating bar2 type:terraform hcl:false sensitive:false value:0
```

After pushing these variable values into TFE, a run of the same configuration produces the same results after the conversion:

```
f0 = is true
f1 = is true
f2 = is true
b0 = is false
b1 = is false
b2 = is false
```

**Comment by fprimex** [comment]
Hi, I merged the work to implement this into master and have tagged a 0.1.0 (yay, first tag!). If you do encounter any trouble, let me know and I will address it ASAP.
