### ISSUE TITLE
Allow setting `-tfe-address` as an environment variable

### ISSUE THREAD

**Issue by kawsark** [hashicorp/tfe-cli#35]
When working with Private Terraform Enterprise server, the `-tfe-address <ptfe_dns>` has to be provided. Instead it would be great if tfe-cli can pick up an environment variable such as `TFE_ADDR`. This will make scripts more reusable when we switch from SaaS to PTFE, or different PTFE servers.

**Comment by fprimex** [comment]
I think `TFE_URL` should work fine, but if not let me know. I'll go ahead and close this, as documentation in general needs an overhaul with so many new commands.
