### ISSUE TITLE
TFE Push Vars should overwrite full variable list

### ISSUE THREAD

**Issue by FraserPol** [hashicorp/tfe-cli#36]
When I push the variables from local, I believe the ideal behaviour would be to overwrite the entire variable list in TFE.

Ie; 
I set 3 variables
foo=bar
zap=bap
x=y

On TFE the result should be;
foo=bar
zap=bap
x=y

Say I re-push the variables removing a value
foo=bar
zap=bap

The result should be;
foo=bar
zap=bap

However the variable not included is not removed and there is no delete function in TFE CLI.

**Comment by fprimex** [comment]
`pushvars` was made to match the `terraform push` behavior, however I added a `-overwrite-all` switch, which should do what you're after. `tfe pushvars -delete` is also available. Let me know if those take care of the issues for you.

**Comment by FraserPol** [comment]
This is perfect thank you!
