### ISSUE TITLE
Update your readme

### ISSUE THREAD

**Issue by tylersmith34** [hashicorp/tfe-cli#37]
You support more actions and your readme was last updated 5 months ago and doesn't list many of the new additions.  Please keep your documentation up-to-date with all releases.

This is the list I see and it doesn't match your doc:
```
$ tfe
Commands:
  tfe configuration-versions <subcommand>          # Manage configuration versions
  tfe help [COMMAND]                               # Describe available commands or one specific command
  tfe oauth-tokens <subcommand>                    # Manage OAuth tokens
  tfe organizations <subcommand>                   # Manage organizations
  tfe policies <subcommand>                        # Manage policies
  tfe policy-checks <subcommand>                   # Manage policy checks
  tfe push <organization>/<workspace> --path=PATH  # Pushes the configuration to the workspace
  tfe runs <subcommand>                            # Manage runs
  tfe teams <subcommand>                           # Manage teams
  tfe variables <subcommand>                       # Manage variables
  tfe version                                      # Show current version
  tfe workspaces <subcommand>                      # Manage workspaces
```

**Comment by fprimex** [comment]
Hi Tyler! Thanks for the report, but I think you are looking at a different `tfe`. That output appears to be for a Ruby implementation available here:

https://github.com/skierkowski/terraform-enterprise-client

While the readme for this project is _definitely_ out of date as well, it's on my list to attend to.

**Comment by tylersmith34** [comment]
Well that's embarrassing...  I forgot I had installed that.

**Comment by fprimex** [comment]
No worries. Since our docs are out of date, I'll leave this open to remind myself to actually get that done.

**Comment by fprimex** [comment]
Major progress was made in the rewrite located here:

https://github.com/hashicorp-community/tf-helper

If that readme sucks just let me know!
