### ISSUE TITLE
Support the .terraformrc

### ISSUE THREAD

**Issue by tylersmith34** [hashicorp/tfe-cli#38]
This CLI doesn't seem to support the CLI configuration for TFE [found here](https://www.terraform.io/docs/commands/cli-config.html).  Instead there's an undocumented feature that we have to export `TFE_TOKEN` to use this CLI.  You should support the `.terraformrc` format since TFE customers already have to use that file to use the OSS CLI.

**Comment by fprimex** [comment]
This is planned, thanks.

**Comment by itoperations-us** [comment]
🔥

**Comment by fprimex** [comment]
Hi! The devel branch has this along with the new `config` command. You can check it out until it is merged.

**Comment by fprimex** [comment]
As mentioned in other issues,`tfe-cli` is being deprecated but I have performed a pretty big rewrite / improvement and that's over here:

https://github.com/hashicorp-community/tf-helper

It has support for the `.terraformrc` in that you can use the `curl-config` subcommand to generate a `curlrc` file which will contain the token from the `.terraformrc` file. If you have any problems with that command and the `curlrc` feature please file an issue over against `tfh`. Cheers!
