### ISSUE TITLE
Release formal versions along side the OSS CLI

### ISSUE THREAD

**Issue by tylersmith34** [hashicorp/tfe-cli#39]
If you want TFE customers to take this seriously, you should too.  This repo has the feel of a pet project and not a supported and trusted tool provided by HashiCorp.   You should consider the following to make this more attractive to customers:

1) keep documentation up-to-date
2) produce a release artifact with a versioning scheme that relates to the TFE product version
2a) requiring customers to clone this repo and `git pull` to stay up-to-date doesn't support CI/CD tooling very well and doesn't allow me to pin versions of this repo along with my version of TFE or PTFE
3) provide support for the full TFE API and not just the pieces previous customers have asked for

**Comment by fprimex** [comment]
Hi Tyler,

We're in the process of helping everyone transition their use cases for `tfe-cli` to `terraform`, the `remote` backend, and the `tfe` provider. This project has always existed to fill in as a stopgap, starting with the deprecation of `terraform push`. Customer support tickets drive the development, and we use this codebase to deliver real working solutions quickly, sometimes within the same day.

But, that's not the long term outlook. I _wouldn't_ suggest setting up a new workflow with `tfe-cli` _if_ your workflow can be accommodated by `terraform`, the `remote` backend, and/or the `tfe` provider. We expect to deprecate this project soon and it will be transition to exactly what you described - mostly a pet project / stopgap codebase / `curl` reference. Where it will live is yet to be determined.

The future of `tfe` has been getting discussed a lot lately, in terms of whether we would go "all in" and do a full client in Go, or transition to other solutions. Transitioning to other solutions is the way we're going.

If you have a use case that is currently _requiring_ `tfe-cli` that can't be accomplished via the other means mentioned, please let us know and we'd be happy to have support and solutions look over it.

Cheers,

Brent W.
