### ISSUE TITLE
Invalid HCL reported by TFE after tfe pushvars

### ISSUE THREAD

**Issue by mengesb** [hashicorp/tfe-cli#49]
I'm trying to push a google `credentials.json` in HCL map form:

```hcl
credentials = {
  key = "value",
  key2 = "value2",
  ...
}
```

Seems that it isn't pushing correctly when the value contains `//`, because terraform enterprise reports:

```text
1 error occurred:
	* Invalid HCL in variable "credentials": At 4:6: expected '/' for comment
```

Here's an example of a credentials json map:

```hcl
credentials={
  type="service_account",
  project_id="some-project-name",
  private_key_id="1234567890abcdef",
  private_key="-----BEGIN PRIVATE KEY-----\n...content...\n-----END PRIVATE KEY-----\n",
  client_email="user@project.iam.gserviceaccount.com",
  client_id="0123456789",
  auth_uri="https://accounts.google.com/o/oauth2/auth",
  token_uri="https://oauth2.googleapis.com/token",
  auth_provider_x509_cert_url="https://www.googleapis.com/oauth2/v1/certs",
 
 client_x509_cert_url="https://www.googleapis.com/robot/v1/metadata/x509/user%40project.iam.gserviceaccount.com"
}
```

Pertaining to the message, the private_key has `/`'s in it, and also the `auth_uri`, `token_uri` and `auth_provider_x509_cert_url` have `//`. I'm wondering if it isn't being messed up because of the `private_key` value ?

**Comment by fprimex** [comment]
Hi @mengesb , please give `tf-helper` (`tfh`) over [here](https://github.com/hashicorp-community/tf-helper) a try. This project has been deprecated as mentioned in the [readme](https://github.com/hashicorp/tfe-cli#this-project-has-been-deprecated-and-is-no-longer-maintained). I'll be happy to look into anything that doesn't work with `tfh`.
